[deployment]
name = "My Plugin"
description = "A very cool Kite plugin"

[module.build]
out = "plugin.wasm"

[server]
host = "127.0.0.1"
port = 8080
public_url = "http://localhost:3000/api"

[server.sdk]
js_script_path = "../js-sdk/dist/index.js"
js_declaration_path = "../js-sdk/dist/index.d.ts"

[server.app]
public_url = "http://localhost:3000/app"

[server.postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
db_name = "kite"