version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${PG_HOST_PORT:-5432}:5432"
    volumes:
      - kite-local-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kite
      PGUSER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  kite-local-postgres:
