[deployment]
name = "My Plugin"
description = "A very cool Kite plugin"

[module.build]
out = "plugin.wasm"

[server]
host = "127.0.0.1"
port = 8080
public_url = "http://localhost:8080"

[server.app]
public_url = "http://localhost:3000"

[server.postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
db_name = "kite"

[server.engine.limits]
max_total_time = 10_000
max_execution_time = 100
max_memory_pages = 250 # 16MB
max_host_calls = 25
deployment_pool_max_total = 5
deployment_pool_max_idle = 2
deployment_pool_min_idle = 0