[plugin]
key = "ping@merlin.gg"
name = 'Ping'
description = 'A simple !ping and /ping command'
type = 'go'

events = ["DISCORD_MESSAGE_CREATE", "DISCORD_INTERACTION_CREATE"]
permissions = ["DISCORD_MESSAGE_CREATE"]

[[plugin.commands]]
type = 'chat'
name = 'ping'
description = 'Pong!'

[plugin.default_config]
channel_id = "0987654321"
