on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build
        working-directory: kite-docs
        run: |
          npm install
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 42459c568b12d0902eeac887235b0c41
          projectName: kite-docs
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: kite-docs
          wranglerVersion: "3"
